### ISSUE TITLE
Index name must have a prefix and suffix

### ISSUE THREAD

**Issue by johnculviner** [vanthome/winston-elasticsearch#10]
I'd prefer my index just be 'foo-bar' and not 'foo-bar-2015-10-30' which is consistent with this thing before it was re-written. Perhaps an exposed hook to getIndexName is in order so that one can do whatever they want?

**Comment by johnculviner** [comment]
The old one just used to support 'indexName' which i suppose could be the one that is used if it is specified rather than the prefix and suffix. Let me know if you think this is a good idea. I could do a PR but for now I'm using the old one (0.1.1).

It might be wise to bump up to version 1.0 too since semantic versioning isn't really being followed in this case:

```
Given a version number MAJOR.MINOR.PATCH, increment the:
MAJOR version when you make incompatible API changes,
MINOR version when you add functionality in a backwards-compatible manner, and
PATCH version when you make backwards-compatible bug fixes.
Additional labels for pre-release and build metadata are available as extensions to the MAJOR.MINOR.PATCH format.
```

**Comment by jackdbernier** [comment]
It would be nice to add it back and also I agree with bumping the version to 1.0. Specially with regards of this other breaking change #9

I do not use winston anymore (for no specific reasons) but I think it safe to say that if you have the time you should submit a PR.

**Comment by vanthome** [comment]
Ok, I have added support for the `index` property which allows to specify just an index name to use, without pattern. Regarding visioning, I think I want to go for 1.0.0 only after having it run in production for a longer time.

**Comment by jackdbernier** [comment]
@vanthome I would suggest using prerelease versioning as proposed here https://github.com/npm/node-semver#prerelease-identifiers

`1.0.0.beta.0` for instance. It's your call after all.

**Comment by johnculviner** [comment]
Thanks @vanthome you beat me to it!
