### ISSUE TITLE
ResponseError: circuit_breaking_exception

### ISSUE THREAD

**Issue by athenawisdoms** [vanthome/winston-elasticsearch#117]
I have a long-running node.js script that takes over 4 hours to run. At the start of the script, It logs a message using `winston` and `winston-elasticsearch` to indicate that the script has started running. After 4 hours, it logs another message to indicate the time taken and that the script has finished running. 

The winston logger is configured to log to console, to file, and to elasticsearch (ELK stack).

However, when it tries to log the 2nd message, there is an error:

> ResponseError: circuit_breaking_exception

This message was successfully logged to console, to log file, but not to elasticsearch.

Any ideas why this is happening? Thank you!

**logger.js**

```
const options = {
    elasticsearch: {
        level: 'debug',
        clientOpts: {
            node: 'http://elkstack.example.com:9200',
            maxRetries: 5,
            requestTimeout: 60000,
            sniffOnStart: false,
            auth: {
                username: 'elastic',
                password: 'password'
            }
        }
    }

    ...
}

let logger = winston.createLogger({
    exitOnError: false,
    transports: [
        new (winston.transports.DailyRotateFile)(options.file),
        new winston.transports.Console(options.console),
        new ElasticsearchWinston(options.elasticsearch)
    ]
});
```

**System**
- Ubuntu 18.04.3
- Node v12.15.0
- winston 3.2.1
- winston-elasticsearch 0.8.3

**Error Stack Trace**

```
(node:16296) UnhandledPromiseRejectionWarning: ResponseError: circuit_breaking_exception
    at IncomingMessage.<anonymous> (/home/athenawisdom/foo/node_modules/@elastic/elasticsearch/lib/Transport.js:294:25)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)
```

**Comment by vanthome** [comment]
It looks like that's an issue in the ES client. Please check first with the parameters and long lived idle connections to ES for the ES client. I assume other people have discussed this. I cannot research that now.

**Comment by Razzeee** [comment]
https://github.com/elastic/elasticsearch-js/issues/1095#issuecomment-590891758
suggests, that there might be a bug in this library

**Comment by bruegth** [comment]
suggests, that it could related to this: https://github.com/vanthome/winston-elasticsearch/issues/103#issuecomment-603216196

**Comment by bruegth** [comment]
Also it would be good to handle the response error 429 (circuit_breaking_exception/OOM) different, because connection test with an ping will be successful after an 429 error. Suggests, that maybe just make a longer timeout in case of an 429 or otherwise ignore 429 in bulkwrite to drop log messages.

**Comment by vanthome** [comment]
I guess we can close this by now. Please reopen if it persists.
