### ISSUE TITLE
bulk writer response.body doesn't exist

### ISSUE THREAD

**Issue by flymans** [vanthome/winston-elasticsearch#118]
Hello, after upgrading winston-elasticsearch from **0.8.2** to **0.8.4** I got this error: 
```
TypeError: Cannot read property 'errors' of undefined
    at /mnt/c/Users/pas/dev/scripts/node_modules/winston-elasticsearch/bulk_writer.js:97:13
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

**UPD**: same for **0.8.3**
**0.8.2** works fine

**Comment by litti** [comment]
This is duplicate to #114 and fixed with (not yet merged) b6a740f11450e85bf397b9c48eabad3d2c2ba185
