### ISSUE TITLE
TypeError: winston_elasticsearch_1.default is not a constructor

### ISSUE THREAD

**Issue by MeepManager** [vanthome/winston-elasticsearch#122]
When I try to import the module in node.js & TypeScript 3.7.4, my program crashes:

```javascript
import * as winston from "winston";
import ElasticsearchTransport from "winston-elasticsearch";
...
    const esTransport = new ElasticsearchTransport({
        level: "info",
        clientOpts: {
            node: "http://localhost:9200",
        },
    });
```
It actually compiles fine, except my program crashes with the error: `TypeError: winston_elasticsearch_1.default is not a constructor`

I believe this has to do with the way the default `ElasticsearchTransport` is being exported. My recommendation would be to drop this default and have a proper index.d.ts file

Versions:
```
        "winston-elasticsearch": "0.8.5",
        "winston": "3.2.1",
        "winston-transport": "4.3.0",
```

**Comment by vanthome** [comment]
can you make a proposal for this pls? we have an `index.d.ts` already...

**Comment by SET001** [comment]
same issue here

**Comment by SET001** [comment]
was able to run ti when changed default export to named. I can to a PR if you like.

**Comment by vanthome** [comment]
yes, pls. PR

**Comment by SET001** [comment]
@vanthome can you update npm?

**Comment by goferito** [comment]
What about importing like:

```js
import { ElasticsearchTransport } from "winston-elasticsearch"
```

**Comment by SET001** [comment]
@goferito  that is actually what my PR did
https://github.com/vanthome/winston-elasticsearch/pull/126/commits/ca3d9c74a88077d9b992456dfbd0125df9a9ab34#diff-168726dbe96b3ce427e7fedce31bb0bcR136

**Comment by goferito** [comment]
I see. But it's not yet published to npm.
