### ISSUE TITLE
ElatsicsearchTransport type export does not conform to the index.js export

### ISSUE THREAD

**Issue by dejv78** [vanthome/winston-elasticsearch#129]
Hi,

I'm using winston-elasticsearch, version 0.8.7 in a monorepo project, and I believe I found a discrepancy between ElasticsearchTransport export in index.d.ts and index.js.

Somehow, this doesn't seem to cause any trouble in "regular" projects, but it reveals itself in monorepo projects, either using lerna npm hoisting, or yarn workspaces.

The problem seems to be this:
In order for the ElasticsearchTransport to work in the compiled code, you need to import it like:

`import ElasticsearchTransport from 'winston-elasticsearch';`

However, this causes TS compiler issues. In order to silence them, one needs to import the class like this, instead:

`import {ElasticsearchTransport} from 'winston-elasticsearch';`

This wai, it compiles ok, but in turn, refuses to run, once compiled.

I believe the problem is in this line of index.js:

`module.exports = ElasticsearchTransport;`

Instead, it should be something like: 
```
module.exports = {
  ElasticsearchTransport = ElasticsearchTransport
}
```
Then it would agree with index.d.ts structure.

To silence the compiler errors on ElasticsearchTransport constructor, I currently have to use this hack (or, let's call it ... a workaround :)) :

`new (<any>ElasticsearchTransport)(options)`

Although functional, it is not nice as a permanent solution.

**Comment by marknelissen** [comment]
Since the change in index.js is a breaking change they probably don't want to revert to the export in index.d.ts, the opposite solution would be to modify `export class ElasticsearchTransport extends TransportStream {` to `export default class ElasticsearchTransport extends TransportStream {` so as to align the typescript export with the _pure_ javascript one.

**Comment by AndreasHotelbird** [comment]
I did try the workaround s that @dejv78 is mentioning but with no success. I still get a `TypeError: (intermediate value) is not a constructor` how did you get this working. Would love to hear from you.

**Comment by vanthome** [comment]
Should be good now with release 0.8.8

**Comment by marknelissen** [comment]
I confirm the typing is again correct.

**Comment by jasonperrone** [comment]
Are you guys sure this is is fixed in 0.8.8? 

My package.json:
```
"winston-elasticsearch": "~0.8.8"
```

The Node require:
```
const WinstonElastic = require('winston-elasticsearch');
```

The code:
```
const ElasticTransport = new WinstonElastic(esTransportOpts);
```

The error:
TypeError: WinstonElastic is not a constructor

**Comment by marknelissen** [comment]
@vanthome actually reverted the 0.8.7 _fix_ to the way you have to use the 0.8.6
`const WinstonElastic = require('winston-elasticsearch').ElasticsearchTransport`

But indeed, the readme has not been updated, and still gives the wrong instructions.

**Comment by jasonperrone** [comment]
Thank you @marknelissen

**Comment by dejv78** [comment]
Thanks a lot @vanthome , version 0.8.8 works well...
