### ISSUE TITLE
if fireAndForget and have callback the log will not send

### ISSUE THREAD

**Issue by leibale** [vanthome/winston-elasticsearch#14]
```javascript
var thiz = this;

if (callback && thiz.fireAndForget) {
  return callback(null);
}
```
and if it's not clear, the `return` will stop the function..

**Comment by davibe** [comment]
`fireAndForget` is not even used in the rest of the code so it's not making any sense.

**Comment by leibale** [comment]
https://github.com/vanthome/winston-elasticsearch/blob/master/index.js#L89

**Comment by davibe** [comment]
i mean besides that line that does not make sense, it's not used anywhere else

**Comment by leibale** [comment]
this code has been deleted in b665de10e1c8e231b031835a873fc758a5c1638a
