### ISSUE TITLE
Readme unclear on which version to use

### ISSUE THREAD

**Issue by ryanm** [vanthome/winston-elasticsearch#146]
Thank you for winston-elasticsearch.

I think this line in the Readme:

> For Winston 3.x, Elasticsearch 6.0 and later, use the 0.7.0. For Elasticsearch 6.0 and later, use the 0.6.0.

... should be:

> For Winston 3.x, Elasticsearch **7**.0 and later, use the 0.7.0. For Elasticsearch 6.0 and later, use the 0.6.0.

**Comment by fahminlb33** [comment]
Can confirm, I once tried it on my server and my container keeps crashing. Now I'm downgrading to 0.6.0 and everything works fine.
