### ISSUE TITLE
Possible Typo on Usage?

### ISSUE THREAD

**Issue by Jonathan-Jackson** [vanthome/winston-elasticsearch#154]
Hi!

Love the library!

Just got started with it, and was confused why it wasn't working (latest version), the class pulled back from the USAGE example is actually nested within an object for me:

```
// Doesn't work
const ElasticsearchTransport = require('winston-elasticsearch');

// Works
const { ElasticsearchTransport } = require('winston-elasticsearch');
```

Apologies if this has already been flagged and i'm being dumb, I couldn't see anything within the readme or issues! If this is version related it might be worth adding a comment.

Thanks for the hard work!

**Comment by vanthome** [comment]
Thx for the hint
