### ISSUE TITLE
ElasticSearch index error - valuable error info is lost

### ISSUE THREAD

**Issue by eye1** [vanthome/winston-elasticsearch#155]
![image](https://user-images.githubusercontent.com/4639650/93933438-f555a400-fd21-11ea-8922-6d7d74bd8067.png)
![image](https://user-images.githubusercontent.com/4639650/93933473-043c5680-fd22-11ea-8d1c-bd7f483c331d.png)

It would be very helpful if this info is propagated via error object and could be used later when logger error is handled

```
logger.on('error', (error) => {
   apm.captureError(error);
   console.error('Error caught', error);
});
```

**Comment by PaliiucEvghenii** [comment]
agree, at the moment it is very difficult to determine the problem on a live system without additional information

**Comment by ruscon** [comment]
@vanthome Could you help speed up the solution to this problem?

**Comment by eye1** [comment]
Very primitive solution but it would do it's job would be to convert this block:

```
          if (item.index && item.index.error) {
            debug('elasticsearch index error', item.index);
            throw new Error('ElasticSearch index error');
          }
```

Into something like this:

```
          if (item.index && item.index.error) {
            debug('elasticsearch index error', item.index);
            const err = new Error('ElasticSearch index error');
            err.caused_by = item.index.error;
            throw err;
          }
``` 

What do you think?

**Comment by ruscon** [comment]
@eye1 Yep. 
Or create a custom `Error` class

**Comment by eye1** [comment]
Is there a way I can contribute to this fix? I tried to branch the repo, but don't have permission.

**Comment by vanthome** [comment]
Sorry for my late reply! Can you please provide a pull request for this?

**Comment by eye1** [comment]
I have opened the PR
