### ISSUE TITLE
Flush function

### ISSUE THREAD

**Issue by andarilhoz** [vanthome/winston-elasticsearch#156]
I dont really know how transports work in winston, but, it would be great if we could call a flush method to send all logs to elasticsearch immediatly.

I'm using this plugin on a AWS lambda function, and i wish i could send all messages before aws freezes my function

**Comment by carrasco39** [comment]
#158 would do it

**Comment by vanthome** [comment]
Added in 0.11.0.

**Comment by JannikZed** [comment]
some kind of docs would be great for that feature ..  I was looking for it as well because of a serverless environment.

**Comment by vanthome** [comment]
see here: https://github.com/vanthome/winston-elasticsearch#manual-flushing
