### ISSUE TITLE
Can't start With Log error

### ISSUE THREAD

**Issue by fargozhu** [vanthome/winston-elasticsearch#16]
node_modules/winston-elasticsearch/index.js:94
    message,
           ^
SyntaxError: Unexpected token ,
    at exports.runInThisContext (vm.js:73:16)

**Comment by jackdbernier** [comment]
This module requires a version of node that supports ECMAScript 2015 (ES6). What version of node are you using ? You may need to upgrade or start your application with the `--harmony` flag.

If upgrading is not an option, you can consider using babel https://babeljs.io/.

**Comment by jackdbernier** [comment]
I agree this is not obvious from the start. This should be highlighted in the README file.

**Comment by fargozhu** [comment]
I'll give it a try...many thanks!

**Comment by fargozhu** [comment]
Works with the flag on.
