### ISSUE TITLE
BulkWriter retry logic causes duplicates.

### ISSUE THREAD

**Issue by stephenjtyler2** [vanthome/winston-elasticsearch#165]
In bulkwriter, if a write returns any errors it retries the entire batch up the max retries count.    If one or more items in the batch succeeded and one or more failed, the bath retries cause the successful items to get duplicated.     It should remove the items that were successfully inserted before doing the retries.    This can happen if you have dodgy mapping for instance which only some log messages fall foul of.

Also while bulkwriter takes retryLimit as an opt, the transport does not pass it, so it always ends up with the default 5 retries.   Should really expose that opt all they way up as a transporter opt.   At the moment this means that if the above happens, the successful entries end up getting duplicated so you have 6 copies of each written to your index.

**Comment by luthv** [comment]
also IMHO the default retryLimit set at 400 retries is too high

**Comment by vanthome** [comment]
fixed with version `0.15.3`.
