### ISSUE TITLE
ElasticSearch index error: Open Distro Security not initialized for indices:data/write/bulk[s]

### ISSUE THREAD

**Issue by epechuzal** [vanthome/winston-elasticsearch#172]
We have been using this package for a while, but noticed that occasionally our applications crash with this error:

```
unhandled rejection Error: ElasticSearch index error
    at /var/app/current/node_modules/winston-elasticsearch/bulk_writer.js:135:25
    at Array.forEach (<anonymous>)
    at /var/app/current/node_modules/winston-elasticsearch/bulk_writer.js:132:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  caused_by: {
    type: 'security_exception',
    reason: 'Open Distro Security not initialized for indices:data/write/bulk[s]'
  }
}
```

I am not sure what this means - our ElasticSearch cluster settings have not changed, and when I restart the application everything works fine again (until this error comes back at some random time).

Is there anything you can suggest? Is it possible to catch this error and attempt to write the logs at a later time?

**Comment by litti** [comment]
This seems to be an Elasticsearch issue: https://discuss.opendistrocommunity.dev/t/open-distro-security-not-initialized/489

**Comment by epechuzal** [comment]
That's fair - is there a way to catch errors in bulk writing? What happens now is I write logs and they go through, but when the bulk_writer throws it also makes my application stop as its uncaught.

**Comment by litti** [comment]
Hm, do you have the actual very version installed? You can also have a look at https://github.com/vanthome/winston-elasticsearch/blob/master/bulk_writer.js#L178-L185 - there the error is emitted and you should be able to handle it in your code. Did you see the example here: https://github.com/vanthome/winston-elasticsearch#usage? If nothing of these helps, please provide some code.

**Comment by epechuzal** [comment]
@litti thank you for pointing out the error handlers! I will implement and come back if I still see issues: my guess is this will fix my problems though
