### ISSUE TITLE
How to connect elasticsearch with credentials?

### ISSUE THREAD

**Issue by migka2012** [vanthome/winston-elasticsearch#174]
I tried these codes below but it did not work because I saw no index created in elasticsearch.
Please help
`var winston = require('winston');
var Elasticsearch = require('winston-elasticsearch');

const esTransportOpts = {
  level: 'info',
  clientOpts: {
    node: 'http://localhost:9200',
    auth:{
      username: 'elastic',
      password: 'jmango360'
    }
  }
};

const elasticSearch = new Elasticsearch(esTransportOpts);
const logger = winston.createLogger({
  transports: [
    elasticSearch
  ]
});
logger.info(message);`

**Comment by migka2012** [comment]
As I was encountering an issue "ElasticsearchTransport is not a constructor", I downgraded wiston-elasticsearch to 0.7.12. As a result, the issue above occurred.

I can fix the issue by using the latest version of wiston-elasticsearch and
`import {ElasticsearchTransport} from "winston-elasticsearch";`

**Comment by agracia-foticos** [comment]
Same issue!!!
