### ISSUE TITLE
Open Distro Security not initialized.

### ISSUE THREAD

**Issue by ximiluliyi** [vanthome/winston-elasticsearch#175]
Run command：
curl -XGET https://localhost:9200 -u admin:admin -k

return:

Open Distro Security not initialized.

![image](https://user-images.githubusercontent.com/40221289/104913323-65222580-59c8-11eb-8fb0-ead4f75951b9.png)

**Comment by litti** [comment]
This seems to be a configuration or Elasticsearch issue: https://discuss.opendistrocommunity.dev/t/open-distro-security-not-initialized/489

**Comment by vanthome** [comment]
...If not please reopen.
