### ISSUE TITLE
Failed to index to ES 7.9.3

### ISSUE THREAD

**Issue by tvedtorama** [vanthome/winston-elasticsearch#177]
We use winston-elasticsearch on a number of servers, where most have older ES instances.  On our 7.9.3 server we get this cryptic message when trying to log data:

```
only write ops with an op_type of create are allowed in data streams
```

I traced that down "data streams", which I admittedly have no idea what is, then tried to configure W-E with {dataStreams: false}.  However, the errors persists.  What can be the reason?

I am running on 0.13.0

**Comment by vanthome** [comment]
can you try to set the `datastream` config option to `true` and let me know whether that fixed it?

**Comment by tvedtorama** [comment]
@vanthome - yes it did!

Thank you - but this is bit confusing to me.  What's causing this configuration, which works with < 7.9 to fail on 7.9?

**Comment by vanthome** [comment]
well obviously the logger tries to write the data into a data stream, maybe that's also because of the index pattern you use. 
Can you tell me whether the issue got fixed by my proposal?

**Comment by mskec** [comment]
I have the same issue after upgrading from ES 7.10.x to ES 7.16.x.

Error is gone with `dataStrea: true`, but then I cannot change `indexPrefix` and `indexSuffix`, and the index defaults to `logs-app-default`.

I use version `0.15.6` (aws/ES licensing issue).
```typescript
indexPrefix: `logs-${serviceName}`,
indexSuffixPattern: 'YYYY.MM',
```

Do you have an idea why is the error happening?
