### ISSUE TITLE
Specifying types in bulk requests is deprecated

### ISSUE THREAD

**Issue by willi2i** [vanthome/winston-elasticsearch#178]
Im sure it will be my setup as new to Elasticsearch, but I am plagued with this error/warning message 

warning: '299 Elasticsearch-7.11.0-8ced7813d6f16d2ef30792e2fcde3e755795ee04 "[types removal] Specifying types in bulk requests is deprecated."',

Help would be greatly received

versions: 
"winston": "^3.3.3",
"winston-elasticsearch": "^0.12.3"
elasticsearch:7.11.0

**Comment by vanthome** [comment]
Fixed in release 0.15.0. Pleas try and reopen if the issue persists.
