### ISSUE TITLE
Duplicate documents

### ISSUE THREAD

**Issue by brunoosilva** [vanthome/winston-elasticsearch#187]
Hello,

I'm having a problem with an application that receives a lot of requests and multithread, and this log is at the beginning, but for some reason, sometimes it's duplicating the documents. What could be happening?

![image](https://user-images.githubusercontent.com/3465257/120384807-05844100-c2fd-11eb-9a15-1c2c7455b089.png)

**Comment by vanthome** [comment]
Are you using the latest version and can you try to set `buffering` to `false` and tell me whether it's still occurring?

**Comment by weathered-fire-2600** [comment]
I faced a similiar issue... But in my case only one log entry got written to elasticsearch. Setting the option `buffering` to `false` solved this problem.

winston-elasticsearch 0.15.6
@elastic/elasticsearch 7.13.0

**Comment by brunoosilva** [comment]
Hi @vanthome , work fine, tks!
