### ISSUE TITLE
indexSuffixPattern and indexPrefix are throwing errors when set

### ISSUE THREAD

**Issue by Benraay** [vanthome/winston-elasticsearch#188]
option
indexSuffixPattern:"[YYYY.MMM.DD]"

is throwing this error
indexError: {
    type: 'invalid_index_name_exception',
    reason: 'Invalid index name [logs-YYYY.MMM.DD], must be lowercase',
    index_uuid: '_na_',
    index: 'logs-YYYY.MMM.DD'
  },

and if I set 
indexPrefix:"logs-mycustom"

esTransport Error caught ResponseError: illegal_argument_exception
    at onBody (/Users/***/***/***/node_modules/@elastic/elasticsearch/lib/Transport.js:337:23)

**Comment by vanthome** [comment]
The problem is that you should specify the pattern as `YYYY.MMM.DD` and not `[YYYY.MMM.DD]`.
