### ISSUE TITLE
Error during bulk writer flush is not recoverable

### ISSUE THREAD

**Issue by theodorick** [vanthome/winston-elasticsearch#19]
If there is an error while writing to Elasticsearch, the next bulk write is never scheduled. This can easily be reproduced by running a local Elasticsearch node and cycling it off and on during logging. After coming back online the code never resumes sending to ES. Your promise chain does not call schedule() when there is an error, so how is it supposed to resume?

BulkWriter.prototype.tick = function tick() {
  debug('tick');
  const thiz = this;
  if (!this.running) { return; }
  this.flush()
  .catch((e) => {
    throw e;
  })
  .then(() => {
    thiz.schedule();
  });
};

**Comment by vanthome** [comment]
There have been some changes to this in 0.4.0 can you re-check this?

**Comment by quex46** [comment]
probably, related to [#25](https://github.com/vanthome/winston-elasticsearch/issues/25).
what server version you are using?
