### ISSUE TITLE
Cannot connect to ES

### ISSUE THREAD

**Issue by dyaacov** [vanthome/winston-elasticsearch#201]
Hi All,

I have an openSearch service  in AWS (former ElasticSearch)

when I use curl in the same ecs pod, **it works**.
when I try with winston, I get a general error

-- same code worked in a different environment with EKS and ElasticSearch --

**Cannot connect to ES
at /app/node_modules/winston-elasticsearch/bulk_writer.js:245:20**

any tip where I should begin to investigate?

Thanks
Dekel

**Comment by vanthome** [comment]
Maybe try to create an ES Client outside of winston-elasticsearch and pass it using the `client` option?

**Comment by dyaacov** [comment]
After using DEBUG

`DEBUG=* node LoggerTEST.js`
Found the error:

(node:29001) UnhandledPromiseRejectionWarning: ProductNotSupportedError: The client noticed that the server is not Elasticsearch and we do not support this unknown product.

**Comment by machao23** [comment]
@dyaacov I ran into the same issue, can you please tell me how to solve this issue?
