### ISSUE TITLE
0.14.0 introduces a breaking change for ES 7.7

### ISSUE THREAD

**Issue by thiago-negri** [vanthome/winston-elasticsearch#205]
Opening the issue just in case you want to add that to the README/CHANGELOG file. I'm currently running ES 7.7 and I can't upgrade the plugin past 0.13.0, because 0.14.0 requires the new index template API, which is only available on ES 7.8+.

The specific change that breaks it:
https://github.com/vanthome/winston-elasticsearch/commit/e3f0b7a52ef37d9f4b2a31f28c30f59bf2e56b85#diff-8fd595d5134a276ec8bae2762c4b3ff120b3a121a16282147614daccb90e1f01R278

**Comment by vanthome** [comment]
added a hint.
