### ISSUE TITLE
How to add some extra fields to the mapping.

### ISSUE THREAD

**Issue by karkul** [vanthome/winston-elasticsearch#21]
Hi Everybody,

I'm looking for a way about how to include some additional fields to the basic MappingTemplate to do the information make more sense for us. But I have not luck to find a good example, so can you please give me a hand with that?

I tried to modify the transformer.js & the index-template-mapping.json files but it doesn't work.

We want to add some information like: module nada and device id in the data structure of winston-elasticsearch and be able to index it on Elasticsearch.

Thanks in advance

**Comment by Razzeee** [comment]
So were you able to adress this?

**Comment by tuanlc** [comment]
Hello @karkul ,
I'm facing the same problem, did you solve it? Please share with me.

Thanks in advance!

**Comment by vanthome** [comment]
As clearly visible in the documentation of this module, you can provide your own mapping template via the `mappingTemplate` option. Also you probably would want have a wrapper of the logger which would add the additional information or alternatively you might be able to add them with a custom transformer script.

**Comment by tuanlc** [comment]
Thank you for your quick your quick reply! It is clear to me.
