### ISSUE TITLE
Conditionally logging to some indexes

### ISSUE THREAD

**Issue by AbraaoFarah** [vanthome/winston-elasticsearch#213]
In my project i have the following WinstonModuleOptions:

`
export const winstonConfig: WinstonModuleOptions = {
  levels: { verbose: 5 }
  level: 'verbose',
  transports: [
    new ElasticsearchTransport(defaultOptions),
    new ElasticsearchTransport(customOptions),
  ],
}
`

Where as you can see i can create multiples transporters, and each one will transport every single log to the instantiated index.

But my question is, can i dinamically change the indexPrefix option? Or even, can i have customs transporters that doesnt log (or that only logs) some logs based on the log message?

I have tried using the transformer method but could only change the level property, It seems changing the indexPrefix in the transformer method is too late, because the _index has already been created with the original prefix.

**Comment by vanthome** [comment]
RTFM: https://github.com/vanthome/winston-elasticsearch#options
The `indexPrefix` can be a function.
