### ISSUE TITLE
unwork with elasticserach 5.0

### ISSUE THREAD

**Issue by superbogy** [vanthome/winston-elasticsearch#25]
unwork with elasticserach 5.0. use es2.3.5 success, then upgrade to se5.0, it doesn't work; please check~!(use the latest package version2.3， winston and winsto-elasticsearch)

**Comment by sspilleman** [comment]
I can confirm that at least "Elasticsearch.prototype.log" function is not called so nothing is even sent to elasticsearch....

**Comment by quex46** [comment]
If you try to log error on bulk writing it will say:
```request [/_bulk] contains unrecognized parameter: [consistency]"```

So if you comment [this line](https://github.com/vanthome/winston-elasticsearch/blob/master/bulk_writer.js#L67) (to omit "consistency" param) then it will start to work fine. Seems its not a problem of module itself, but sdk according to the docs [here](https://www.elastic.co/guide/en/elasticsearch/reference/1.4/docs-bulk.html#bulk-consistency)
