### ISSUE TITLE
Update element

### ISSUE THREAD

**Issue by MatthD** [vanthome/winston-elasticsearch#26]
Hello, first of all thanks for this open-source usefull project .

In my project we use Winston-es to insert & we want now to update some documents , is this possible with Winston-es ?

thks

**Comment by vanthome** [comment]
Here you can see how it's possible to find an entry using the transport:

https://github.com/vanthome/winston-elasticsearch/blob/master/test/test.js#L75

But modifying is not implemented yet. It should be no problem to implement it outside however. Also updating ES documents is not recommended. You should rather delete and re-index.
