### ISSUE TITLE
CPU usage when Elasticsearch is down

### ISSUE THREAD

**Issue by libor-vilimek** [vanthome/winston-elasticsearch#27]
We have serious issues when our Elasticsearch server go down, the usage of CPU starts growing rapidly.

It would be really nice, if this module first tries to reconnect if some request fails on Timeout. And after it looks ok, it starts sending all the logs it couldnt send before.

Also growing of memory usage can kill the whole app, if it grows too much. An option "how much logs you keep" when cant log to Elastic would be nice. When you reach limit, it starts to discard them. We have non-critical usage sometimes (like monitoring), but this monitoring is able to crash the whole app - better to lose some logs in this case.

**Comment by cjy37** [comment]
+1

**Comment by vanthome** [comment]
Sure, this all makes sense. you can pass your own ES client and use the ` maxRetries` option. Actually, the default is 3 so it should not run mad. But probably whenever a new message is logged, the client tries to connect again. So we would need some kind of circuit breaker. Dies that match your observation?

https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html

**Comment by vanthome** [comment]
Problem solved with latest release.
