### ISSUE TITLE
Allocation failed - JavaScript heap out of memory

### ISSUE THREAD

**Issue by avitaler** [vanthome/winston-elasticsearch#29]
Hi, 
Received error ....  using winston and winston-elasticsearch
any idea ? 
Node 6.10 
winston 2.31 
winston-elasticsearch 0.5

==== JS stack trace =========================================

Security context: 000002A973FCFB61 <JS Object>
    1: log [C:\project\dist\server\node_modules\winston\lib\wins
ton\logger.js:~109] [pc=000000A6B0078D1A] (this=0000037A4E023269 <JS Object>,level=000001472E47B4B9 <String[4]: info>)
    2: arguments adaptor frame: 2->1
    3: info [C:\project\dist\server\node_modules\winston\lib\winston\common.js:~51] [pc=000000A6B006D32B] (this=0000037A4E023269 <JS Object>,ms.
..

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

**Comment by vanthome** [comment]
Nope, maybe it's related to #27. Was ES unavailable for some time when this happened? Also can you reproduce with the latest version of this module?

**Comment by vanthome** [comment]
This should no longer happen as buffering is not limited.
