### ISSUE TITLE
"status" field name not written in elasticsearch

### ISSUE THREAD

**Issue by sebastianovide** [vanthome/winston-elasticsearch#32]
this is **not** working. Not errors thrown... the log is displayed in the console but not in elasticsearch.... 
```
    logger.info("something here", {
        status: "something",
    });
```
this **is** working (see that the status field has been renamed to sstatus with two s).
```
    logger.info("something here", {
        sstatus: "something",
    });
```
It was working until last night....

any ideas ?

**Comment by vanthome** [comment]
Hi, no idea. Can you re-check with latest version?

**Comment by vanthome** [comment]
@sebastianovide can you reproduce this with the latest version?
