### ISSUE TITLE
Especify document Id

### ISSUE THREAD

**Issue by MirkoTV** [vanthome/winston-elasticsearch#33]
@vanthome Is there a way to specify the document Id we will send to elasticsearch for each log we send to winston-elasticsearch? This became really important in my scenario since I want to override/update a document in elastic but I dont find the way whitout this feature.  Something like the "document_id" we have in logstash

**Comment by vanthome** [comment]
Hmm, can you point out where and how this is specified through the winston interface? I think winston does not know about something like a document ID. You can however just generate your own and push it to winston like any other JSON structure. Would that serve your purpose?

**Comment by vanthome** [comment]
Can you please answer my question?

**Comment by rajpootmohan** [comment]
Same issue for me too. I am not able to specify document id for a document while pushing using winston-elasticsearch.

**Comment by vanthome** [comment]
Same question then for you:
can you point out where and how this is specified through the winston interface? I think winston does not know about something like a document ID. You can however just generate your own and push it to winston like any other JSON structure. Would that serve your purpose?

**Comment by vanthome** [comment]
Any news here?
