### ISSUE TITLE
Cannot find module 'index-template-mapping.json'

### ISSUE THREAD

**Issue by MGlahn** [vanthome/winston-elasticsearch#36]
If I leave out ` ensureMappingTemplate: false` in the transport options object I will get following error:
`Cannot find module 'index-template-mapping.json'`
If I "force it" to get the file by adding __dirname to the path (`const rawdata = fs.readFileSync(__dirname + '/index-template-mapping.json'); `) then I get an error in the end of my ES trace:
........
`
    }
  }
  <- 400
  {
    "error": {
      "root_cause": [
        {
          "type": "illegal_argument_exception",
          "reason": "unknown setting [index.cache.field.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
        }
      ],
      "type": "illegal_argument_exception",
      "reason": "unknown setting [index.cache.field.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
    },
    "status": 400
  }`

**Comment by krismeister** [comment]
Try to use the json in a generic object instead of a json file you're loading in node. Pass the object in the options object as `mappingTemplate`

**Comment by afreeland** [comment]
I had same issue...

**Comment by krismeister** [comment]
I'm not sure its not an issue. He assumes you want to edit the Json to meet your needs, and pass it in as a generic object.

**Comment by vanthome** [comment]
please try with latest release
