### ISSUE TITLE
file path broken.

### ISSUE THREAD

**Issue by null4bl3** [vanthome/winston-elasticsearch#37]
https://github.com/vanthome/winston-elasticsearch/blob/e053a69daf9b16501746d26c8b7fc140a08f7182/index.js#L183

This line should be changed to:

` const rawdata = fs.readFileSync(__dirname + '/index-template-mapping.json');`

In order to actually reference the json file.

The reference is also not providing any method of error handling which can cause memory leaks and other nasties on heavy loads, and will fail in later versions of Nodejs.

Assign me if you want me to fix it.

**Comment by vanthome** [comment]
please try with latest release

**Comment by vanthome** [comment]
Please try with now published 0.5.5 and re-open if not fixed.
