### ISSUE TITLE
Space in Debug log name

### ISSUE THREAD

**Issue by krismeister** [vanthome/winston-elasticsearch#38]
This plugin uses the string 'bulk writer' as its name for [debug](https://github.com/visionmedia/debug) Unfortunately by having a space in the name, it is not possible to silent this output specifically:

**This does not work**
```
// notice the -bulk write below.
$ DEBUG='*,-express:router*,-nodemon:watch,-bulk writer' nodemon app/server.js 
```

**This does work but is not ideal**
```
// notice the -bulk*
$ DEBUG='*,-express:router*,-nodemon:watch,-bulk*' nodemon app/server.js 
```

**Feature Request**
The debug log be given a name without the space character, and consider making a more specific identifiable name for this `debug` log. Its standard to use `:` colon instead of spaces in `debug` names.

**Comment by vanthome** [comment]
Sorry, totally missed this PR. Can you rebase it and re-create it?

**Comment by vanthome** [comment]
Solved with last version. Debug key is called just `winston:elasticsearch` now.

**Comment by vanthome** [comment]
Please check solution an open again if not fixed.
