### ISSUE TITLE
Please publish v0.5.4 on npm

### ISSUE THREAD

**Issue by eschwartz** [vanthome/winston-elasticsearch#40]
v0.5.1 [introduced a major bug](https://github.com/vanthome/winston-elasticsearch/blame/e053a69daf9b16501746d26c8b7fc140a08f7182/index.js#L183) (#37). This bug was [fixed in v0.5.4](https://github.com/vanthome/winston-elasticsearch/commit/260cccb593d4c1b04abebc54688316d5a26ddf7a#diff-168726dbe96b3ce427e7fedce31bb0bcR184). But v0.5.4 was never published to npm, which means the latest version of this library is still broken.

Can you please publish v0.5.4 to the npm repo. Thank you!

**Comment by philipstanislaus** [comment]
@vanthome please publish the latest version of this project to npm. Thanks for the great work! 👍

**Comment by vanthome** [comment]
Did you verify, that it works for you?

**Comment by vanthome** [comment]
I just pushed some more changes.

**Comment by philipstanislaus** [comment]
@vanthome thanks for your updates! 

Not sure we are talking about the same thing though – I am referring to this package: https://www.npmjs.com/package/winston-elasticsearch which was last published 2 months ago and stands on version 0.5.3. 

Would be great if you could run `npm publish` to push up v0.5.5. Thanks!

**Comment by vanthome** [comment]
Done, published 0.5.5.

**Comment by philipstanislaus** [comment]
Thanks!
