### ISSUE TITLE
HTTP response status 200 but body declares error status 400

### ISSUE THREAD

**Issue by afreeland** [vanthome/winston-elasticsearch#41]
I was logging some data to elasticsearch that looked like the following. 

A simple message, an evt name, an **array of objects**, and some rewrites for general app information
```
logger.info(`Tableau marks selected for ${_workbookName}/${_sheetName}` , {
                                    evt: 'tableauMarksSelection',
                                    marks: [ {..}, {..} ]
                                })
```

After utilizing this in elasticsearch for awhile it seemed that the **marks** field didnt really need to be an object...that I could just stringify the array and that would be sufficient for us.  

Now **marks** gets stringified like the following
```
logger.info(`Tableau marks selected for ${_workbookName}/${_sheetName}` , {
                                    evt: 'tableauMarksSelection',
                                    marks: JSON.stringify([ {..}, {..} ])
                                })
```

After doing so I noticed that this particular log would NEVER send.  So I started wrapping `try/catches` around, nothing.  Wired up the `logger.on('error', ...)`, nothing.  

I knew it was something with this library b/c my console logs are working fine, as well as logging to file...so decided to debug the winston-elasticsearch module. After debugging through I finally crept up on the following code

**elasticsearch/src/lib/transport.js**
```
function respond(err, body, status, headers) {
    if (aborted) {
      return;
    }

    self._timeout(requestTimeoutId);
    var parsedBody;
    var isJson = !headers || (headers['content-type'] && ~headers['content-type'].indexOf('application/json'));

    if (!err && body) {
      if (isJson) {
        parsedBody = self.serializer.deserialize(body);
        if (parsedBody == null) {
          err = new errors.Serialization();
          parsedBody = body;
        }
      } else {
        parsedBody = body;
      }
    }

    // does the response represent an error?
    if (
      (!err || err instanceof errors.Serialization)
      && (status < 200 || status >= 300)
      && (!params.ignore || !_.include(params.ignore, status))
    ) {

      var errorMetadata = _.pick(params.req, ['path', 'query', 'body']);
      errorMetadata.statusCode = status;
      errorMetadata.response = body;

      if (status === 401 && headers && headers['www-authenticate']) {
        errorMetadata.wwwAuthenticateDirective = headers['www-authenticate'];
      }

      if (errors[status]) {
        err = new errors[status](parsedBody && parsedBody.error, errorMetadata);
      } else {
        err = new errors.Generic('unknown error', errorMetadata);
      }
    }
```

It appears that this code handles a lot of other potential statuses outside of a 200...but this particular error sends back a 200 in the http response but inside the body declares **errors: true** and a **status: 400** inside the index response.
```
{
{
    "took": 3,
    "errors": true,
    "items": [
        {
            "index": {
                "_index": "logs-2017.11.21",
                "_type": "log",
                "_id": "AV_gQwfT3jrEIURbei0L",
                "status": 400,
                "error": {
                    "type": "mapper_parsing_exception",
                    "reason": "object mapping for [fields.marks] tried to parse field [marks] as object, but found a concrete value"
                }
            }
        }
    ]
}
```

Once I seen this body response I was able to test by simply by changing the `marks` field to `tableauMarks`

```
logger.info(`Tableau marks selected for ${_workbookName}/${_sheetName}` , {
    evt: 'tableauMarksSelection',
    tableauMarks: JSON.stringify(pairs)
})
```
 And then the logs started going back into elasticsearch and my hunt was over =)

Was wanting to put this out here in case anyone else ran across it as this error is hidden deep within and does not easily expose itself.

ElasticSearch: 5.6.3 (docker container)

**Comment by vanthome** [comment]
Can you please check again with the latest release and let me know?
