### ISSUE TITLE
reconnect/retry

### ISSUE THREAD

**Issue by afrozl** [vanthome/winston-elasticsearch#42]
I wanted to verify if this is expected behavior. If my ES instance is off-line,  logging stops as expected. However, once the ES instance is back on-line, logging does not resume. I have to restart the app to force a reconnection to ES and resume logging. Is this by design?

**Comment by vanthome** [comment]
This is related to https://github.com/vanthome/winston-elasticsearch/issues/27 where I explained that by default the ES client has a ` maxRetries` of `3` before it gives up. You could provide your own client and override this. I agree however, that or a module like this, this is not ideal. I will see whether I can come up with a built-in retry mechanism.

**Comment by afrozl** [comment]
that would be great. Restarting app(s) for a logging outage seems backwards

**Comment by vanthome** [comment]
With the last release I have enhanced the situation considerably. The strategy is now that the lib is infinity retrying to connect at a reasonable frequency
