### ISSUE TITLE
support for elasticsearch 6.X

### ISSUE THREAD

**Issue by sharonass** [vanthome/winston-elasticsearch#43]
Hello,

I'm trying to use this lib with elasticsearch 6.0 and I get problems with the template, when i changed to custome template I get no error but I dont see it indexing to elasticsearch

Does this lib supports EC v6.X, if not is there any plan to support it soon?

**Comment by vanthome** [comment]
I have released a new version with some changes to the default mapping, it has been tested with 6.x. Please try.

**Comment by sharonass** [comment]
which release?

**Comment by vanthome** [comment]
the latest obviously.

**Comment by nofear87** [comment]
@sgilligan I use default mapping and yours, but both ends with the following error:

Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.05.16] as the final mapping would have more than 1 type: [_doc, log]' }

**Comment by vanthome** [comment]
that's probably because you try to change an already existing index. Can you try to delete the index and then try again?

**Comment by nofear87** [comment]
@vanthome thanks for fast response. I have delete it. Then set ensureMappingTemplate = true and provide the provided mappingTemplate (from @sgilligan). The error remains.

**Comment by nofear87** [comment]
also defaults not working: 

const elasticClient = new elasticsearch.Client({
    host: 'localhost:9200',
});

const esTransportOpts = {
    level: 'info',
    client: elasticClient
};

**Comment by vanthome** [comment]
Are you sure that nothing else, no other application or app instance is creating the type `_doc`? Just try to run the tests with a plain local ES instance and you will see it works.

**Comment by nofear87** [comment]
I run a fresh installer docker elk stack. Indices are empty.

**Comment by sgilligan** [comment]
sorry @nofear87 I didn't come across that error in my setup

**Comment by vanthome** [comment]
I also don't see that this is the module's fault. We use `_doc` now as mapping type because it's the default in ES https://github.com/vanthome/winston-elasticsearch/blob/master/index-template-mapping.json#L11. Something must use/ create a log mapping. Maybe if you are using a ready made ELK stack, it launches Logstash which is doing that. Try a plain ES instance please.

**Comment by xuming314** [comment]
I get this error too.

1.run elasticsearch:
```
docker run --name elastic --rm -p=9200:9200 -p=9300:9300 -e=discovery.type=single-node docker.elastic.co/elasticsearch/elasticsearch:6.3.0
```

2.run app:
```
const winston =require('winston');
const winston_elasticsearch =require('winston-elasticsearch');
let logger=new winston.Logger({transports:[new winston_elasticsearch({
    level:'debug',
    clientOpts:{host:'http://127.0.0.1:9200'}
})]})
```
3.get error:
```
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
Elasticsearch index error { type: 'illegal_argument_exception',
  reason: 'Rejecting mapping update to [logs-2018.06.16] as the final mapping would have more than 1 type: [_doc, log]' }
```
