### ISSUE TITLE
unknown setting - index.cache.field.type

### ISSUE THREAD

**Issue by vsrinivasdsd** [vanthome/winston-elasticsearch#46]
hello,

i have setup elasticsearch(6.2.4) and kibana(6.2.4) in my local docker installation.
the docker images of both have been taken from the official docker hub site.

i have a node js application in which i am using winston(2.4.2), elasticsearch(14.2.2) and winston-elasticsearch(0.5.9) to try to log to my elasticsearch setup.

below is my code:
initialize logger -------------------------------
```
const es = require("elasticsearch");
const Elasticsearch = require("winston-elasticsearch");
const winston = require("winston");

const esClient = new es.Client({
            host: "<ip address>:9200",
            log: "trace",
            index: "oversight",
            sniffOnStart: true
          });

        this.elasticLogger = new (winston.Logger)({
            levels: this.logLevels.levels,
            transports: [
                new Elasticsearch({ client: esClient, colorize: true  })
            ],
            exceptionHandlers: [
                new Elasticsearch({ client: esClient, colorize: true })
            ]
            exitOnError: false,
            handleExceptions: true
        });

        this.elasticLogger.on("error", (err) => {
            console.log(`Elastic Logger failed at ${new Date()} with error ${err} !`);
        });
```
-------------------------------------------------
i also have a transport for console logging which is working fine and the connection between elasticsearch and kibana containers are also up and running.

when my application's docker container is up and starts to log, following are the stdout info:
```
Elasticsearch TRACE: 2018-04-25T14:43:36Z
  -> GET http://<ip address>:9200/_nodes/_all/http?filter_path=nodes.*.http.publish_address%2Cnodes.*.name%2Cnodes.*.hostname%2Cnodes.*.host%2Cnodes.*.version
  
  <- 200
  {
    "nodes": {
      "2knkp79ZS0W_iCTWiHaGxQ": {
        "name": "oversight_elasticsearch",
        "host": "<ip address>",
        "version": "6.2.4",
        "http": {
          "publish_address": "<ip address>:9200"
        }
      }
    }
  }
```

```
Elasticsearch TRACE: 2018-04-25T14:43:36Z
  -> HEAD http://<ip address>:9200/
  
  <- 200
```

but after some tries to create template logs i get the following error:

```
Elasticsearch TRACE: 2018-04-25T14:43:36Z
  -> PUT http://<ip address>:9200/_template/template_logs?create=true
 { ... a whole bunch of default settings...}

  <- 400
  {
    "error": {
      "root_cause": [
        {
          "type": "illegal_argument_exception",
          "reason": "unknown setting [index.cache.field.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
        }
      ],
      "type": "illegal_argument_exception",
      "reason": "unknown setting [index.cache.field.type] please check that any required plugins are installed, or check the breaking changes documentation for removed settings"
    },
    "status": 400
  }
```

upon searching the current github issues details and other pages, i found that the setting - index.cache.field.type has not been a valid setting since version 0.26.0.

please guide me on how to proceed with the setup or this issue. is there any other additional setup or setting that i might have missed ?

any help is greatly appreciated!

**Comment by vanthome** [comment]
I think you are right, this seems to be an ancient setting and even all these:

```
      "cache": { "field.type": "soft" },
      "query": { "default_field": "message" },
      "store": { "compress": { "stored": true, "tv": true } },
      "routing": { "allocation.total_shards_per_node": 1 }
```

seem not to be supported anymore. My question is, did you see this error only by tracing the HTTP traffic or was this also logged in the exception handler?

**Comment by vsrinivasdsd** [comment]
all the trace output i listed above, i get it on the Kitematic console, which is the STDOUT for all logs generated from my application.
there is no indication that any of the logs were generated because of an exception.

i have attached a text file with all the STDOUT logs from the moment my application connects to elasticsearch till the said [root cause] log, to get a better picture.

[Logs.txt](https://github.com/vanthome/winston-elasticsearch/files/1950232/Logs.txt)

**Comment by vanthome** [comment]
Hi, can you confirm that this is gone with the latest release?

**Comment by vanthome** [comment]
ok, closing this now.
