### ISSUE TITLE
Question about buffer size & time

### ISSUE THREAD

**Issue by exalted** [vanthome/winston-elasticsearch#48]
Hey there,

Thank you for all you've been doing here.

Looking at the code I couldn't tell for how long and what size limit is for the buffer used when a connection to Elasticsearch is lost.

I tested this with a trivial setup and it seems like for at least couple of minutes logs sent will not be lost even if ES is down/stopped, and when it comes back up all the logs are available as if they were successfully sent at the right timestamp.

* Is this handled in `winston-elasticsearch` or perhaps `winston` itself?
* For how long logs will be buffered before they're lost _forever_ in case Elasticsearch is down for a considerable time?
* Is there a size (either in terms of number of logs, or byte-size) limit on how much data is going to be buffered before they're lost?

Could you please give some feedback? 🙏

**Comment by vanthome** [comment]
Hi, you can just check in the code, logs that are not written are buffered [in a buffer](https://github.com/vanthome/winston-elasticsearch/blob/master/bulk_writer.js#L14) that is only limited by memory available on the system/ node process. So after some time the process will blow. It would be a useful enhancement to support a user specified maximum together with a ring-buffer implementation.

**Comment by exalted** [comment]
Thanks @vanthome for replying back…

Ouch! I was thinking the same, but wanted to make sure before making any claims here.
