### ISSUE TITLE
Arbitrary winston3 fields?

### ISSUE THREAD

**Issue by jwalton** [vanthome/winston-elasticsearch#53]
With Winston3, if I run:

```js
logger.info({message: "Test", foo: "bar"});
```

There doesn't seem to be a way to get `foo: "bar"` into elasticsearch.  The `transformer` isn't passed the entire `info` object from Winston - it only gets a `{level, message, meta}` object?

**Comment by jwalton** [comment]
As a suggested fix, add a `format` option, which takes a standard Winston formatter; whatever is returned from the formatter is what is written to ES.  If `format` is present, `transformer` is ignored.  This way you can write a function that has full access to the `info` object from Winston, this is more consistent with the other Winston transports (most take a `format` option), and it's backwards compatible.

**Comment by vanthome** [comment]
You can solve that by supplying a transformer. By default winston-elasticsearch assumes log statemenets like `logger.info('textual message', [optional object])` You are trying to log `logger.info([object])`. You can either stringify the object in the transformer or just route it to the `transformed.fields`. There are quite some combinations and also the mapping can be/ might need to be changed depending on your solution.

**Comment by jwalton** [comment]
The problem is, the transformer doesn't have access to the original object.  From [this bit here](https://github.com/vanthome/winston-elasticsearch/blob/master/index.js#L92-L98):

```js
    const logData = {
      message,
      level,
      meta,
      // timestamp: this.opts.timestamp()
    };
    const entry = this.opts.transformer(logData);
```

So if I call:

```js
    logger.info({message: "Test", foo: "bar"});
```

The transformer is going to be called with this object:

```js
{
    message: "Test",
    level: "info",
    meta: undefined
}
```

So the transformer doesn't have access to the `foo` field.

**Comment by jwalton** [comment]
Two other possible fixes for this:

* Add a `rawTransformer` option - if it's there, call that instead of `transformer`.
* [Here](https://github.com/vanthome/winston-elasticsearch/blob/master/index.js#L98), call `transformer(logData, info)`, so transformers can access the raw `info` object.

I'm happy to submit a PR.

**Comment by vanthome** [comment]
I got your point now, I have introduced a change that should work for you w/o complicating things further with a raw-transformer. Please check and close if ok.

**Comment by jwalton** [comment]
This will do it; I'd recommend getting rid of [the delete lines](https://github.com/vanthome/winston-elasticsearch/blob/master/index.js#L88-L89) though - delete is a bit of a performance black hole in V8.  Thanks!

**Comment by vanthome** [comment]
Hmm, yea, good point, it could be done in the transformer at will but for now I think I will keep it.
