### ISSUE TITLE
TypeError: Cannot read property 'timestamp' of undefined

### ISSUE THREAD

**Issue by rojarand** [vanthome/winston-elasticsearch#54]
I have 

> TypeError: Cannot read property 'timestamp' of undefined
> at new Elasticsearch (.../node_modules/winston-elasticsearch/index.js:18:14)
> 

when I use my custom logger. 
logger.js code (copied from Readme#Usage):

```javascript 
var winston = require("winston");
var Elasticsearch = require("winston-elasticsearch");
 
var esTransportOpts = {
  level: "info"
};
winston.add(new winston.transports.Elasticsearch(), esTransportOpts);
module.exports = winston;
```

logger usage example:
```javascript
var logger = require("./logger");
...
logger.log("info", "some message");
```
The problem is with opts variable. It is used without checking if it is undefined

> winston-elasticsearch version: "0.7.0"
> node version: v8.6.0

Try replace in index.js
line 17:
```javascript
this.opts = opts || {};
```
with
```javascript
if(!opts){
    opts = {};
}
this.opts = opts;
```

**Comment by vanthome** [comment]
why are you not creating your logger as documented:
https://github.com/vanthome/winston-elasticsearch#usage
Please note that Winston 3.0.0 requires you to migrate your previous code.
Also I don't see why this `this.opts = opts || {};` should not work as intended, this is a known idiom. Can you try a newer version of Node?

**Comment by rojarand** [comment]
1) There were two ways presented in documentation how to initialize winston with winston-elasticsearch. I tried use the first one, which was mentioned earlier in logger.js excerpt. Now I noticed this "first" way is not in docs.
2) The first way of setting up logger created instance of Elasticsearch where constructor input - `opts` was undefined. You assumed it is possible by checking it `this.opts = opts || {};`. After this line `opts` are still undefined but `this.opts` are not. And in next line of the code you try to read from `opts`: `if (!opts.timestamp) {` what causes the error.

**Comment by rojarand** [comment]
Oh... I took winston initialization not from github readme but from https://www.npmjs.com/package/winston-elasticsearch

**Comment by vanthome** [comment]
So does it work now?

**Comment by rojarand** [comment]
Yes. It is working in case when winston initialization is done according to https://github.com/vanthome/winston-elasticsearch#usage.

**Comment by vanthome** [comment]
good, don't ask me why this is but I don't care and just use the new way.
