### ISSUE TITLE
Outdated README?

### ISSUE THREAD

**Issue by arjd4science** [vanthome/winston-elasticsearch#56]
The CHANGELOG suggests that winston-elasticsearch supports buffering when ES is down (https://github.com/vanthome/winston-elasticsearch/blob/master/CHANGELOG.md#057--2018-02-14), but the README still has it down as a `todo/unsupported` item (https://github.com/vanthome/winston-elasticsearch/blob/master/README.md#unsupported--todo).

**Comment by vanthome** [comment]
fixed
