### ISSUE TITLE
Request Timeout after 30000ms

### ISSUE THREAD

**Issue by ragu-nathan** [vanthome/winston-elasticsearch#66]
I am using winston-elasticsearch@0.6.0 and winston@2.4.3 logging in Kibana. I am getting below error.
`{ Error: Request Timeout after 30000ms
    at /var/app/current/node_modules/elasticsearch/src/lib/transport.js:354:15
    at Timeout.<anonymous> (/var/app/current/node_modules/elasticsearch/src/lib/transport.js:383:7)
    at Timeout.<anonymous> (/var/app/current/node_modules/async-listener/glue.js:188:31)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  status: undefined,
  displayName: 'RequestTimeout',
  message: 'Request Timeout after 30000ms',
  body: undefined }`

I have added the flag for not exit. `winston.exitOnError = false;` and added the option `handleExceptions: true` in transport. But still i am getting this error.

**Comment by shadialtarsha** [comment]
I am having the same problem.
And I think it is related to the tcp connection.
But I can't figure it out

**Comment by vanthome** [comment]
yes, I can confirm that this lib cannot be used with Logstash directly, it lust logs like logstash.
