### ISSUE TITLE
Invalid transport, must be an object with a log method.

### ISSUE THREAD

**Issue by gaukharaya** [vanthome/winston-elasticsearch#71]
winston v3.1.0
winston-elasticsearch v0.7.5

Hello, I hope someone can help me with this issue? Is this a valid way to add Elasticsearch transport? 
```
winston.add(winston.transports.Elasticsearch, {
            clientOpts: {
                host: 'http://uks-elk-01-p:9200'

            },
            indexPrefix: 'rhino-node-server'
});
```

The effect I am trying to achieve is for all winston logs to implicitly log to Elasticsearch. I don't want to add Elasticsearch transport to every new logger I create, so instead I have a `WinstonConfigurator.js` where I specify all winston transports and then I use that configuration for every new logger created. 

Unfortunatey I get: 

```
winston-transport\legacy.js:18
    throw new Error('Invalid transport, must be an object with a log method.');

```

I think there was something remotely related on https://github.com/winstonjs/winston-loggly/pull/53

**Comment by vanthome** [comment]
Can you check this module:

https://github.com/restorecommerce/logger

I'm doing what you describe basically and it works.

**Comment by vanthome** [comment]
Any update on this?
