### ISSUE TITLE
Packaging basics

### ISSUE THREAD

**Issue by four43** [vanthome/winston-elasticsearch#79]
There seem to be some basic packaging issues with the library, mainly:

- Lack of tags and proper versioning
- Including extraneous files like .eslintrc in npm bundle
- Git has your specific .vscode IDE settings which is typically frowned upon. 

I can make a pull request to fix these things once I get it to work. I'm bumping into the ever popular `Rejected mapping` bug like #49

**Comment by vanthome** [comment]
Thx, I will take on these nut not the last one. I think nothing speaks against keeping the main authors editor settings in the repo.
I never heard about this issue in a while. Make sure you use the latest version and

**Comment by vanthome** [comment]
Btw. I don't see a problem with proper versioning, do you?

**Comment by four43** [comment]
I was mainly speaking to the lack of tags. It's hard to go see what was in a previous version if the tags aren't provided. It relies on downloading multiple versions from NPM and hacking around in there. Thanks for looking into those.

I see some of the confusion. It's because .npmignore files are flawed by design _shakes fist_. You have your .vscode file properly ignored in git, but .npmignore overrides that and bundles that into the uploaded package. DUMB.

Here were my thoughts on IDE settings before I realized that was the case, I thought they were in git too: 

Generally putting your IDE settings into a specific project's git repo is bad practice because it's meta data only and not related to the code or project in any way except you. With bad IDEs it can leak secrets, but at best it's configuring my IDE to point to folders and things specific to your computer. I'm looking for some references around the internet that say to commit some things that are related to code analysis, building, etc. Luckily software has grown since then more towards the Unix principal, do your one thing well. Those tasks are now split up, we have:
- Linting/analysis settings via eslint and editorconfig (good those are comitted)
- Build targets and test config via npm's package.json

Anyone with any IDE can take advantage of those utilities, they are not vendor specific, which is great.

Thanks for the help!

**Comment by vanthome** [comment]
You have persuaded me here, I made the relevant changes and we will have tags from now on.

**Comment by four43** [comment]
Thanks @vanthome!
