### ISSUE TITLE
Clarification for `buffering: false`

### ISSUE THREAD

**Issue by raphaelts3** [vanthome/winston-elasticsearch#80]
Hello!

First of all, I love the package and it has been very useful in my projects.
That said, I think the way `buffering: false` works is incorrect, or should be more clear in the documentation.
In my opnion, at least, when `buffering` is `false` the package should send every message, but what really happens is that the buffer is limited to a single message and discard the others that came at the same time.
So, I hope it could be either modified to send every message or more clear in the documentation.

Besides that, great package, great work and thank you.

**Comment by Snelius30** [comment]
Yea, u are right I guess. But for full support, it requires to rework entire bulkWrite module. Feel free to implement.

**Comment by vanthome** [comment]
You are right, I have fixed this by introducing full support for non-buffered writes now.
