### ISSUE TITLE
Index created faster, than ensured Mapping template. 

### ISSUE THREAD

**Issue by lambrent** [vanthome/winston-elasticsearch#83]
mapping Template is created, but log reach ES faster than template is created. Mapping template available only on next index.

**Comment by vanthome** [comment]
hmm, so you say we have a racing condition here?
Can you try to instantiate the transport and before you log the first message to invoke this method?

https://github.com/vanthome/winston-elasticsearch/blob/baa2c44bee2eb29223335334b2185dc750f37a2d/bulk_writer.js#L111

This is responsible to ensure the template.

**Comment by vanthome** [comment]
@lambrent any news on this?

**Comment by vanthome** [comment]
@lambrent any news on this?

**Comment by Munawwar** [comment]
https://github.com/vanthome/winston-elasticsearch/pull/142 fixed this to wait till template is created/confirmed before starting to log
