### ISSUE TITLE
0.7.10 was published with .git directory

### ISSUE THREAD

**Issue by haggholm** [vanthome/winston-elasticsearch#85]
`winston-elasticsearch` @ `0.7.10` was published to npm with the `.git` directory. Presumably this was unintended, and it can cause a variety of exciting errors with various npm operations returning `EISGIT`.

**Comment by vanthome** [comment]
Strange, I checked and in the history of `.npmignore ` there was never `.git` I have recently added `.gitignore`, maybe npm interprets `.gitignore` somehow. Will check.

**Comment by stefanomasini** [comment]
Is it something that can be fixed soon (like now)? I wonder if I should wait for the fix or revert to an older release.

**Comment by skeet** [comment]
Same question as above.

Our build pipeline is currently broken.
