### ISSUE TITLE
Field to send log to elasticsearch

### ISSUE THREAD

**Issue by YahyawiAF** [vanthome/winston-elasticsearch#86]
I use this code to send logs to elasticsearch for my node application 

`var elasticsearch = require('elasticsearch');
const logger = winston.createLogger();

var client = new elasticsearch.Client({
  host: 'http://172.23.0.3:5000',
  log: 'info'
});

client.ping({
  requestTimeout: 30000,
}, function(error) {
  if (error) {
    console.log(error)
      console.error('elasticsearch cluster is down!');
  } else {
      console.log('Everything is ok');
  }
});

logger.add( new winston_elasticsearch({
  client,
  index:"logging"
}));
`

by the way logstash.conf is like this 
`input {
	tcp {
		port => 5000
	}
}
output {
	elasticsearch {
		hosts => "elasticsearch:9200"
	}
}`

I get this  from **client.ping**
`{ Error: Request Timeout after 30000ms
    at /usr/app/node_modules/elasticsearch/src/lib/transport.js:355:15
    at Timeout.<anonymous> (/usr/app/node_modules/elasticsearch/src/lib/transport.js:384:7)
    at ontimeout (timers.js:498:11)
    at tryOnTimeout (timers.js:323:5)
    at Timer.listOnTimeout (timers.js:290:5)
  status: 408,
  displayName: 'RequestTimeout',
  message: 'Request Timeout after 30000ms' }`

and i git this from logStash console
`  | [2019-04-26T12:24:31,485][WARN ][logstash.filters.json    ] Error parsing json {:source=>"message", :raw=>"HEAD / HTTP/1.1\r", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'HEAD': was expecting ('true', 'false' or 'null')
"; line: 1, column: 6]>}Source: (byte[])"HEAD / HTTP/1.1`

any solution please

**Comment by manelOyez** [comment]
add this in your logstash.conf so it can parse json
filter{ json { source =>  "message"  }  }

**Comment by YahyawiAF** [comment]
> add this in your logstash.conf so it can parse json
> filter{ json { source => "message" } }

yes i do that and i get this in logstash console

>  | [2019-04-26T14:49:13,590][WARN ][logstash.filters.json    ] Error parsing json {:source=>"message", :raw=>"Connection: keep-alive\r", :exception=>#<LogStash::Json::ParserError: Unrecognized token 'Connection': was expecting ('true', 'false' or 'null')
"; line: 1, column: 12]>}ource: (byte[])"Connection: keep-alive

**Comment by vanthome** [comment]
This does not seem to be an issue related to this project but rather something logstah related. Closing it, feel free to reopen if needed.
