### ISSUE TITLE
Index Name swap based ob indexSuffixPattern 

### ISSUE THREAD

**Issue by whoisstan** [vanthome/winston-elasticsearch#94]
Hi,
I set my indexSuffixPattern to `MM.DD.YYYY_hh.mm` because I wanted to see if a new index is used if the date pattern rolls over from one period to the next. Does that only work when it rolls over from one day to the other?
Thank you,
Stan

**Comment by vanthome** [comment]
Hi, no that is decided with every new log message anew. Have you checked that the pattern is compatible with dayjs: https://github.com/iamkun/dayjs ?
BG

**Comment by whoisstan** [comment]
Got this this all figured out, the implicit day based pattern was fully sufficient.
