### ISSUE TITLE
Signing HTTP Requests

### ISSUE THREAD

**Issue by whoisstan** [vanthome/winston-elasticsearch#98]
Hi there,
is there a way to use signed HTTP requests to Elasticsearch using your framework? 

https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html

There is a node.js example in the code base. I be happy to help too.

Thank you very much,
Stan

**Comment by vanthome** [comment]
In the node.js example they just make plain HTTP requests and do not use the ES client at all. This is not an option for this module. I would propose you ask this question on the original ES client here:
https://github.com/elastic/elasticsearch-js
whether they do or will support this.
